stream {
    # Specifies the main log format.
    log_format main '$remote_addr - [$time_local] $status';
    # Sets the path, format, and configuration for a buffered log write.
    # Buffer log writes to speed up IO, or disable them altogether
    access_log /var/log/nginx/stream.log main buffer=16k;
    # proxies SSH requests to SSH server
    include conf.d/ssh-stream.inc;
}
